name: building-block

on: push

jobs:
    echo-hello:
        runs-on: ubuntu-latest
        steps:
            - name: say hello
              run: echo "Hai Hello World"
             
    echo-goodbye:
        runs-on: ubuntu-latest
        steps:
            - name: success step
              run: |
                echo "I will sucess"
                exit 0

            - name: say goodbye
              run: echo "Goodbye"